In [1]:
%cd '/app'

/app


In [2]:
%load_ext autoreload
%autoreload 2

In [5]:
from sage.all import *
import sys
sys.path.append('src')

from time import time

import numpy as np
from src.border_basis_lib.border_basis_sampling import BorderBasisGenerator
from src.border_basis_lib.plot import plot_order_ideals, plot_order_ideal
from src.border_basis_lib.utils import is_order_ideal

In [8]:
degree_bounds = [2, 2]
degree_lower_bounds = [0, 0]

n = len(degree_bounds)
ring = PolynomialRing(GF(7), ['x', 'y'], order='degrevlex')
generator = BorderBasisGenerator(ring)

ret = generator.random_border_basis(degree_bounds, total_degree_bound=5, degree_lower_bounds=degree_lower_bounds)

O = ret['order']
G = ret['basis']
B = ret['border']
P = ret['points']


In [9]:
ideal(G).groebner_basis()

[y^2 - y, x - 2]

In [324]:
ideal(F).groebner_basis()

[1]

In [299]:
from src.border_basis_lib.utils import border, subs, is_regular, keyword_for_numbound, is_order_ideal

print(f'O is order ideal: {is_order_ideal(O)}\n{O}\n')

print(f'points P: \n{P}\n')

print(f'evaluation matrix O(P)=\n{subs(O, P)}')
print(f'regularity of O(P): {is_regular(subs(O, P))}')

O is order ideal: True
[x, 1]

points P: 
[1 6]
[5 2]

evaluation matrix O(P)=
[1 1]
[5 1]
regularity of O(P): True


In [303]:

O = [ring(o) for o in O]
B = [ring(b) for b in B]

OP = subs(O, P)
BP = subs(B, P)

M = BP.augment(OP)
V = M.transpose().kernel().basis()
# V

M * Matrix(V).T

[0 0 0]
[0 0 0]

In [304]:
G = Matrix(B + O) * Matrix(V).T
G = G[0]
G = [ring(g) for g in G]
ideal(G).variety()

[{y: 2, x: 5}, {y: 6, x: 1}]

In [305]:
P

[1 6]
[5 2]

In [257]:
subs(G, P)

[2 2 0]
[6 0 5]